# Generated by Django 5.2 on 2025-05-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/defult_image.png', null=True, upload_to='profile_photos/'),
        ),
    ]
