# Generated by Django 5.2 on 2025-05-02 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_userprofile_photo'),
        ('external_api', '0003_rename_product_orderitem_item_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiclient',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='api_clients', to='core.userprofile'),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
