# Generated by Django 5.2 on 2025-04-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_items_available_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
