# Generated by Django 5.2 on 2025-04-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_items_owned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
