# Generated by Django 5.2 on 2025-05-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_items_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, default='default-product-image.jpg', upload_to='photos/%y/%m/%d'),
        ),
    ]
