# Generated by Django 4.2.23 on 2025-07-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_items_advertise_items_quantity_advertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=22),
        ),
    ]
