# Generated by Django 5.2 on 2025-05-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0004_delete_userbalance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentCard',
        ),
    ]
