# Generated by Django 5.2 on 2025-04-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_category_items_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ('name',), 'verbose_name_plural': 'Items'},
        ),
    ]
