# Generated by Django 5.2 on 2025-04-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_rename_soldout_items_available_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Available_Stock',
            field=models.BooleanField(default=True),
        ),
    ]
