# Generated by Django 5.2 on 2025-04-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_items_for_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='created_by',
            new_name='owned_by',
        ),
    ]
