# Generated by Django 5.2 on 2025-04-21 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_age_userprofile_balance_and_more'),
        ('items', '0009_rename_created_by_items_owned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.userprofile'),
        ),
    ]
