# Generated by Django 5.2 on 2025-05-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
