# Generated by Django 5.2 on 2025-05-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, default='default-product-image.jpg', null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
