# Generated by Django 5.2 on 2025-05-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_alter_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='advertise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='quantity_advertise',
            field=models.IntegerField(default=0),
        ),
    ]
