# Generated by Django 5.2 on 2025-04-22 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_order_buyer_alter_order_seller_payment'),
        ('core', '0005_alter_userprofile_balance_alter_userprofile_photo'),
        ('items', '0010_alter_items_owned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_buyer', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_product', to='items.items'),
        ),
        migrations.AddField(
            model_name='payment',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_seller', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='carts.order'),
        ),
    ]
