# Generated by Django 5.2 on 2025-05-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_remove_payment_order_payment_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='is_successful',
            field=models.BooleanField(default=True),
        ),
    ]
