# Generated by Django 5.2 on 2025-05-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_api', '0004_apiclient_user_profile_delete_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
