# Generated by Django 5.2 on 2025-04-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='created_at',
            new_name='date',
        ),
    ]
