# Generated by Django 5.2 on 2025-05-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0003_alter_deposit_user_alter_paymentcard_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBalance',
        ),
    ]
